# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'CAKK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CAKK

  # Conventions
  pod 'SwiftLint',  '~> 0.50.3'
  pod 'R.swift',    '~> 7.3.0'
  pod 'Then',       '~> 3.0.0'

  # Networking
  pod 'Moya/Combine', '~> 15.0.0'
  
  # Database
  pod 'RealmSwift', '~>10'

  # Layout
  pod 'SnapKit', '~> 5.6.0'
  
  # View
  pod 'lottie-ios', '~> 4.1.3'

  # Image Caching
  pod 'Kingfisher', '~> 7.6.2'

  # Map
  pod 'NMapsMap', '~> 3.16.2'
  
  # UI
  pod 'FloatingPanel',  '~> 2.6.0'
  pod 'EasyTipView',    '~> 2.1'
  pod 'BadgeSwift',     '~> 8.0'
  
  # Combine
  pod 'CombineCocoa', '~> 0.4.1'


end

# Limit minimum deployment target version
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
