# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'CAKK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CAKK

  # Conventions
  pod 'SwiftLint',  '~> 0.50.3'
  pod 'R.swift',    '~> 7.3.0'
  pod 'Then',       '~> 3.0.0'

  # Networking
  pod 'Moya/Combine', '~> 15.0.0'

  # Layout
  pod 'SnapKit',    '~> 5.6.0'
  
  # View
  pod 'lottie-ios', '~> 4.1.3'

  # Image Caching
  pod 'Kingfisher', '~> 7.6.2'

  # Map
  pod 'NMapsMap',   '~> 3.16.2'
  
  # UI
  # pod 'BottomSheetView', :git => 'git@github.com:qwerty3345/BottomSheetView.git', :branch => 'main'
  pod 'FloatingPanel', '~> 2.6.0'
  pod 'EasyTipView', '~> 2.1'
  
  # Combine
  pod 'CombineCocoa', '~> 0.4.1'


end

# Limit minimum deployment target version
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
    shell_script_path = "Pods/Target Support Files/#{target.name}/#{target.name}-frameworks.sh"
    if File::exists?(shell_script_path)
      shell_script_input_lines = File.readlines(shell_script_path)
      shell_script_output_lines = shell_script_input_lines.map { |line| line.sub("source=\"$(readlink \"${source}\")\"", "source=\"$(readlink -f \"${source}\")\"") }
      File.open(shell_script_path, 'w') do |f|
        shell_script_output_lines.each do |line|
          f.write line
        end
      end
    end
  end
end
