# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'CAKK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CAKK

  # Conventions
  pod 'SwiftLint', '~> 0.50.3'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
end